REVOKE ALL ON FUNCTION public.guard_profile_tenant() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.update_updated_at_column() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_super() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_city_admin() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.current_org() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.current_municipality() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.city_scope(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.city_owns_org(uuid) FROM PUBLIC, anon;